version: '3.8'

services:
  petopia-api:
    build: .
    container_name: petopia-api
    env_file:
      - .env
    networks:
      - infra
    restart: unless-stopped
    ports:
      - '127.0.0.1:3000:3000'

networks:
  infra:
    external: true
